### ISSUE TITLE
request like post and like comment post, also comment

### ISSUE THREAD

**Issue by yekayee** [Trukes/threads-api-php-client#19]
**Is your feature request related to a problem? Please describe.**
like post and like comment post, also comment

**Comment by Trukes** [comment]
Hello @yekayee !

I don't understand your issue. Can you be more specific, please?

**Comment by yekayee** [comment]
i mean request fiture like post like commentar and comment on post

**Comment by Trukes** [comment]
I'm sorry but t you need to give more context to the issue.

**Comment by Trukes** [comment]
Im closing this issue since it was not a cleary question
